version: 2.1
jobs:
  build:
    #No. of servers/machines
    parallelism: 1

    docker:
      - image: circleci/ruby:3.0.0-node-browsers

    #application directory change it with your application directory name
    working_directory: ~/granite
    environment:
      TZ: "/usr/share/zoneinfo/America/New_York"
      RAILS_ENV: "test"
      RACK_ENV: "test"

    steps:
      - checkout
      #install sqlite dependency
      - run: sudo apt update && sudo apt install zlib1g-dev libsqlite3-dev
      # Bundle install
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3

      # Setup database
      - run: cp config/database.yml.ci config/database.yml
      - run: bundle exec rake db:create db:schema:load --trace

      # Yarn install
      - run: bin/yarn install --cache-folder vendor/node_modules

      # Generate assets
      - run: bin/webpack
      - run: bundle exec rails webpacker:compile
      # Audit Tests
      - run:
          shell: /bin/bash
          command: bundle exec bundle-audit --update
      # Unit tests
      - run:
          shell: /bin/bash
          command: bundle exec rake test --trace
workflows:
  version: 2
  commit:
    jobs:
      - build